apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.7, pipelines.kubeflow.org/pipeline_compilation_time: '2021-11-13T22:21:48.877433',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.7}
spec:
  entrypoint: pipeline
  templates:
  - name: confusion-matrix
    container:
      args: [--graphpath, /tmp/outputs/graph_path/data]
      command: [python, main.py]
      image: confusion-matrix-sample:latest
      imagePullPolicy: Never
    outputs:
      artifacts:
      - {name: confusion-matrix-graph_path, path: /tmp/outputs/graph_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.7
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "confusion
          matrix", "implementation": {"container": {"args": ["--graphpath", {"outputPath":
          "graph_path"}], "command": ["python", "main.py"], "image": "confusion-matrix-sample:latest"}},
          "name": "confusion matrix", "outputs": [{"name": "graph_path", "type": "UI
          metadata"}]}', pipelines.kubeflow.org/component_ref: '{"digest": "6312c75bb551b4cae3d7398ee45d4eb1aae2b11ac24e18e44c78b5d5ee3d0446",
          "url": "component.yaml"}'}
  - name: pipeline
    dag:
      tasks:
      - {name: confusion-matrix, template: confusion-matrix}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
