version: "3"
services:
  app:
    image: uvicorn-app:latest
    entrypoint: "uvicorn api.main:app --host 0.0.0.0 --port 8080"
    ports:
      - 8080:8080
    volumes:
      - ./models:/opt/app/api/models
