version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
