[package]
name = "ch02_next_phrase_with_binary_search"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
