apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.7, pipelines.kubeflow.org/pipeline_compilation_time: '2021-11-15T21:21:51.089872',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.7}
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks:
      - {name: sample-args-program, template: sample-args-program}
      - {name: sample-args-program-2, template: sample-args-program-2}
  - name: sample-args-program
    container:
      args: [--flag, test]
      command: [python, main.py]
      image: sample-args-switch:latest
      imagePullPolicy: Never
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.7
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "use args",
          "implementation": {"container": {"args": ["--flag", {"inputValue": "sample_flag"}],
          "command": ["python", "main.py"], "image": "sample-args-switch:latest"}},
          "inputs": [{"default": "test", "name": "sample_flag", "type": "String"}],
          "name": "sample-args-program"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "95d0cad553adfd921dee70f0cbd8d98d74c714ff3317fb85479054d75a586be2", "url":
          "component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"sample_flag":
          "test"}'}
  - name: sample-args-program-2
    container:
      args: [--flag, sample]
      command: [python, main.py]
      image: sample-args-switch:latest
      imagePullPolicy: Never
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.7
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "use args",
          "implementation": {"container": {"args": ["--flag", {"inputValue": "sample_flag"}],
          "command": ["python", "main.py"], "image": "sample-args-switch:latest"}},
          "inputs": [{"default": "test", "name": "sample_flag", "type": "String"}],
          "name": "sample-args-program"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "95d0cad553adfd921dee70f0cbd8d98d74c714ff3317fb85479054d75a586be2", "url":
          "component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"sample_flag":
          "sample"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
