version: "3"
services:
  notebook:
    image: jupyter/pyspark-notebook:lab-3.2.9
    container_name: notebook
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/tmp/data
    networks:
      - spark-net
  master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7070:7070
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./data:/tmp/data
    networks:
      - spark-net
  worker:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker
    depends_on:
      - master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://master:7077
    volumes:
      - ./data:/tmp/data
    networks:
      - spark-net
  
networks:
  spark-net:
